-- Создание таблиц для базы данных сосисочной
-- V001__create_tables.sql

-- Таблица продуктов (сосисок)
CREATE TABLE product (
    id bigint generated by default as identity,
    name varchar(255) not null,
    picture_url varchar(255)
);

-- Таблица информации о продуктах (цены)
CREATE TABLE product_info (
    product_id bigint not null,
    name varchar(255) not null,
    price double precision
);

-- Таблица заказов
CREATE TABLE orders (
    id bigint generated by default as identity,
    status varchar(255)
);

-- Таблица дат заказов
CREATE TABLE orders_date (
    order_id bigint not null,
    status varchar(255),
    date_created date default current_date
);

-- Связующая таблица заказ-продукт
CREATE TABLE order_product (
    quantity integer not null,
    order_id bigint not null,
    product_id bigint not null
);
