name: Main workflow
on:
  push:
    branches:
      - main
jobs:
  migrate:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    #### Добавьте шаг с Flyway-миграциями

     # Устанавливаем JDK, который нужен для запуска приложений, написанных на Java (Flyway)
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    # Загружаем и устанавливаем Flyway, чтобы можно было использовать его для управления миграциями
    - name: Install Flyway
      run: |
        echo "Starting Flyway download..."
        curl -L -o flyway-commandline.tar.gz "https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/11.1.0/flyway-commandline-11.1.0-linux-x64.tar.gz"
        echo "Download completed, checking file..."
        ls -la flyway-commandline.tar.gz
        echo "Extracting archive..."
        tar -xzf flyway-commandline.tar.gz
        echo "Archive extracted, listing contents..."
        ls -la flyway-11.1.0/
        echo "Creating symlink..."
        sudo ln -s `pwd`/flyway-11.1.0/flyway /usr/local/bin/flyway
        echo "Symlink created, testing flyway..."
        flyway --version

    # Проверяем, что Postgres работает и доступен перед выполнением миграций, чтобы избежать ошибок подключения
    - name: Wait for Postgres
      run: until pg_isready -h localhost -p 5432; do sleep 1; done

    # Выполняем миграции с помощью Flyway, используя URL подключения и учётные данные для базы данных
    - name: Run Flyway migrations
      run: |
        docker run --rm --network host \
          -v $PWD/migrations:/flyway/sql \
          flyway/flyway:11.1.0 \
          -url=jdbc:postgresql://localhost:5432/store \
          -user=user \
          -password=password \
          migrate

    ### Этот шаг оставьте без изменений
    - name: Download and setup autotests binaries
      run: |
        wget -qO- cloud-services-engineer.gitlab.yandexcloud.net/practicum-cloud-services/dbops-autotests/-/package_files/1/download > dbopstest
        chmod +x ./dbopstest
        mv ./dbopstest /usr/local/bin/dbopstest

    ### Этот шаг оставьте без изменений
    - name: Test
      run: |
        dbopstest \
          -test.v \
          -host=${{ secrets.DB_HOST }} \
          -port=${{ secrets.DB_PORT }} \
          -user=${{ secrets.DB_USER }} \
          -password=${{ secrets.DB_PASSWORD }} \
          -db=${{ secrets.DB_NAME }}
